### PR TITLE
release 0.6 - dsl2 migration

### PR DESCRIPTION
**Pull request by mhebrard**

### CODE REVIEW

**Comment by justinjj24** [comment]
need to fix #62 before merge

**Comment by justinjj24** [comment]
successfully ran `NPM-sample-qc/tests/NA12878-chr14-AKT1_1000genomes-dragen-3.7.6` on a "blank-slate" ec2 (only git, nextflow, java, docker, awscli installed ... no aws-creds provided)

**Comment by justinjj24** [comment]
successfully ran NPM-sample-qc/tests/NA12878_1000genomes-dragen-3.7.6 on a "blank-slate" ec2 (only git, nextflow, java, docker, awscli installed ... no aws-creds provided).

Good to merge with master.

**Review by mhebrard — COMMENTED** [review]
# 2022-11-11
## Added
* Small BAM file of 45Mbp around ATK1 gene for sample NA12878 from DRAGEN 3.7
* Conditional parameters to build docker image on MacOS
* Nextflow manifest
* Test run script for full sample NA12878 from s3://1000genomes-dragen3.7...
## Changed
* Quick strat run instruction on small BAM.
* Improve resources description
* Reference genome staged from s3://1000genomes-dragen-3.7...
* Extend copyright date
* relabel 'sample_id' to 'biosample_id'
## Deprecated
## Removed
* Nextflow syntax moved from DSL1 to DSL2
## Fixed
* Fix run script for quick start
## Security
---
close #25

**Pull request merged**
